// src/services/mockData.js

export const INITIAL_TASKS = [
  {
    id: 'T101',
    wbsCode: '1.1.2',
    projectName: 'Assam Pipeline Expansion Project',
    activityName: 'Trench Excavation & Soil Stabilization',
    location: 'Chainage 12+400 to 14+200 (Sector A)',
    contractor: 'Assam Infra Buildcon',
    startDate: '10 Sep 2026',
    targetEndDate: '18 Sep 2026',
    targetQty: 600,
    completedQty: 450,
    unit: 'meters',
    status: 'In Progress',
    specifications: 'Excavate 1.8m depth trench along designated pipeline corridor. Ensure proper slope stability.',
    photoName: 'trench_sec_a.jpg',
    notes: 'Soft soil observed near chainage 13+100; shoring applied.',
  },
  {
    id: 'T102',
    wbsCode: '1.2.1',
    projectName: 'Assam Pipeline Expansion Project',
    activityName: 'Pipe Stringing & Bending',
    location: 'Chainage 10+000 to 12+000 (Sector B)',
    contractor: 'NorthEast Energy Infra',
    startDate: '11 Sep 2026',
    targetEndDate: '20 Sep 2026',
    targetQty: 400,
    completedQty: 250,
    unit: 'meters',
    status: 'In Progress',
    specifications: 'String 24-inch carbon steel API 5L Grade X65 pipes along the ROW. Perform cold bends where required.',
    photoName: 'stringing_b.jpg',
    notes: 'Cold bending equipment deployed at site.',
  },
  {
    id: 'T103',
    wbsCode: '2.1.0',
    projectName: 'Guwahati Pumping Station',
    activityName: 'Joint Welding & Non-Destructive Testing (NDT)',
    location: 'Pump House Bay #3',
    contractor: 'TechWelding & Engineering Works',
    startDate: '12 Sep 2026',
    targetEndDate: '22 Sep 2026',
    targetQty: 50,
    completedQty: 10,
    unit: 'joints',
    status: 'In Progress',
    specifications: 'Shielded Metal Arc Welding (SMAW) followed by 100% Radiographic Testing (RT) and Ultrasonic Testing.',
    photoName: 'welding_ndt_01.jpg',
    notes: 'Passed initial visual check. 10 joints cleared RT inspection.',
  },
  {
    id: 'T104',
    wbsCode: '2.3.4',
    projectName: 'Guwahati Pumping Station',
    activityName: 'Anti-Corrosion Field Joint Coating',
    location: 'Main Feeder Line Section 2',
    contractor: 'CorroShield India Pvt Ltd',
    startDate: '12 Sep 2026',
    targetEndDate: '15 Sep 2026',
    targetQty: 30,
    completedQty: 0,
    unit: 'joints',
    status: 'Pending',
    specifications: 'Apply heat-shrinkable sleeves on welded joints after surface blast cleaning to Sa 2.5 standard.',
    photoName: '',
    notes: 'Scheduled for afternoon shift post NDT clearance.',
  },
  {
    id: 'T105',
    wbsCode: '3.1.2',
    projectName: 'Duliajan Storage Terminal',
    activityName: 'Hydrostatic Pressure Testing',
    location: 'Test Section #4 (Chainage 0+000 to 5+000)',
    contractor: 'Oil Infra Projects Ltd',
    startDate: '12 Sep 2026',
    targetEndDate: '14 Sep 2026',
    targetQty: 5,
    completedQty: 1,
    unit: 'km',
    status: 'In Progress',
    specifications: 'Pressurize pipeline to 1.5x design operating pressure for 24 hours continuous recording.',
    photoName: 'hydrotest_gauge.jpg',
    notes: 'Pumping water initiated; pressure stabilization ongoing.',
  },
  {
    id: 'T106',
    wbsCode: '3.4.0',
    projectName: 'Duliajan Storage Terminal',
    activityName: 'Backfilling & Ground Restoration',
    location: 'Sector C (Chainage 5+200 to 6+000)',
    contractor: 'Assam Infra Buildcon',
    startDate: '15 Sep 2026',
    targetEndDate: '25 Sep 2026',
    targetQty: 800,
    completedQty: 0,
    unit: 'meters',
    status: 'Pending',
    specifications: 'Place padded sand layer around pipe followed by excavated earth compaction in 300mm layers.',
    photoName: '',
    notes: 'Pending completion of holiday testing.',
  },
  {
    id: 'T107',
    wbsCode: '4.1.1',
    projectName: 'Numaligarh Feeder Line',
    activityName: 'HDD (Horizontal Directional Drilling) River Crossing',
    location: 'Brahmaputra South Bank Crossing',
    contractor: 'Trenchless Drilling Corp',
    startDate: '08 Sep 2026',
    targetEndDate: '18 Sep 2026',
    targetQty: 1200,
    completedQty: 950,
    unit: 'meters',
    status: 'In Progress',
    specifications: 'Execute pilot hole drilling and forward reaming for 30-inch casing under riverbed.',
    photoName: 'hdd_rig_site.jpg',
    notes: 'Reaming phase 2 completed smoothly.',
  },
  {
    id: 'T108',
    wbsCode: '4.2.3',
    projectName: 'Numaligarh Feeder Line',
    activityName: 'Cathodic Protection System Installation',
    location: 'Substation CP-02',
    contractor: 'ElectroProtect Engineers',
    startDate: '12 Sep 2026',
    targetEndDate: '16 Sep 2026',
    targetQty: 12,
    completedQty: 3,
    unit: 'anodes',
    status: 'In Progress',
    specifications: 'Install deep-well sacrificial magnesium anode beds and connect transformer rectifier units.',
    photoName: 'cp_anode_install.jpg',
    notes: 'Anode bed #1 and #2 lowerings completed.',
  },
  {
    id: 'T109',
    wbsCode: '5.0.1',
    projectName: 'Silchar Dispatch Terminal',
    activityName: 'Mainline Valve (MLV) Chamber Concrete Pouring',
    location: 'Station MLV-07',
    contractor: 'Northeast Civil Tech',
    startDate: '12 Sep 2026',
    targetEndDate: '13 Sep 2026',
    targetQty: 85,
    completedQty: 0,
    unit: 'cu.m',
    status: 'Pending',
    specifications: 'Pour M30 grade RCC shuttering concrete for reinforced valve pit walls.',
    photoName: '',
    notes: 'Rebar binding verified by Quality Control engineer.',
  },
  {
    id: 'T110',
    wbsCode: '5.2.0',
    projectName: 'Silchar Dispatch Terminal',
    activityName: 'SCADA Instrumentation & Telemetry Sensor Mounting',
    location: 'Control Room Hub A',
    contractor: 'Automation Systems India',
    startDate: '12 Sep 2026',
    targetEndDate: '17 Sep 2026',
    targetQty: 24,
    completedQty: 6,
    unit: 'sensors',
    status: 'In Progress',
    specifications: 'Mount pressure transmitters, temperature gauges, and fiber optic RTU modules.',
    photoName: 'scada_panel.jpg',
    notes: '6 pressure transmitters wired and signal tested.',
  },
];

// Dual exports for compatibility
export const activities = INITIAL_TASKS;